version: '3.7'

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: classes-scheduler-database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: classes_scheduler
      MYSQL_USER: developer
      MYSQL_PASSWORD: dv1010aa
      MYSQL_ROOT_PASSWORD: classesschedulerroot
    networks:
      - classes-scheduler

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: classes-scheduler-backend
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   networks:
  #     - classes-scheduler

volumes:
  data:
    driver: local

networks:
  classes-scheduler:
    name: classes-scheduler-network