version: '3.7'

volumes:
  postgres-database:
    driver: local
  redis-database:
    driver: local

networks:
  classes-scheduler:
    name: classes-scheduler-network

services:

  database:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    image: classes_scheduler/database
    container_name: classes-scheduler-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=dv1010aa
      - POSTGRES_DB=classes_scheduler
    volumes:
      - postgres-database:/data/postgres
    networks:
      - classes-scheduler

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-database:/home/docker/data
    networks:
      - classes-scheduler

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: classes-scheduler-backend
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   networks:
  #     - classes-scheduler